BFS.loadimages(19, bootlogo, Dos)
BFS.tpla(16,14,"[Secure OS - Setup]")
term.setBackgroundColour(32768)
BFS.tpla(2,16,"[Username]")
BFS.tpla(2,18,"[Password]")
term.setCursorPos(13,16)
term.setBackgroundColour(8)
print("                        ")
term.setCursorPos(13,18)
print("                        ")
term.setCursorPos(13,16)
local input1 = read()
fd = BFS.encr(input1, uname)
term.setCursorPos(13,18)
local input2 = read()
fc = BFS.encr(input2, uname)
if not fs.exists("/system/usr.src") then
f = io.open("/system/usr.src", "w")
end
f:write(fd)
f:write("\n")
f:write(fc)
f:close()
os.reboot()